apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        microsvc: customer
      annotations:
        appmesh.k8s.aws/mesh: shopmesh
        appmesh.k8s.aws/ports: "5000"
        appmesh.k8s.aws/virtualNode: customer-vn
        appmesh.k8s.aws/sidecarInjectorWebhook: enabled

    spec:
      containers:
      - name: customer
        image: janakiramm/service
        imagePullPolicy: Always
        env:       
        - name: "SVC_NAME"
          value: "Customer"  
        - name: "SVC_VER"
          value: "1.0"                        
        ports:
        - name: customer
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    microsvc: customer
spec:
  selector:
    microsvc: customer
  type: ClusterIP
  ports:
   - port: 5000
     name: http
     targetPort: 5000
     protocol: TCP 
