apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  template:
    metadata:
      labels:
        microsvc: product
      annotations:
        appmesh.k8s.aws/mesh: shopmesh
        appmesh.k8s.aws/ports: "5000"
        appmesh.k8s.aws/virtualNode: product-vn
        appmesh.k8s.aws/sidecarInjectorWebhook: enabled

    spec:
      containers:
      - name: product
        image: janakiramm/service
        imagePullPolicy: Always
        env:       
        - name: "SVC_NAME"
          value: "Product"                  
        - name: "SVC_VER"
          value: "1.0"                  
        ports:
        - name: product
          containerPort: 5000
---          
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    microsvc: product
spec:
  selector:
    microsvc: product
  type: ClusterIP
  ports:
   - port: 5000
     name: http
     targetPort: 5000
     protocol: TCP 
